# Generated by Django 5.2.15 on 2026-06-28 16:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('wins', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('next_focus', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('wins', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('next_focus', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('area', models.CharField(choices=[('work', 'Work'), ('health', 'Health'), ('learning', 'Learning'), ('relationship', 'Relationship'), ('personal', 'Personal'), ('business', 'Business'), ('other', 'Other')], default='personal', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('target_date', models.DateField(blank=True, null=True)),
                ('progress_note', models.TextField(blank=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'priority', 'target_date', 'title'],
                'indexes': [models.Index(fields=['status', 'priority'], name='productivit_status_c2ab3d_idx'), models.Index(fields=['target_date'], name='productivit_target__1dc64a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting', 'Waiting'), ('done', 'Done'), ('archived', 'Archived')], default='active', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='productivity.goal')),
            ],
            options={
                'ordering': ['status', 'priority', 'due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('inbox', 'Inbox'), ('next', 'Next'), ('doing', 'Doing'), ('waiting', 'Waiting'), ('done', 'Done'), ('canceled', 'Canceled')], default='inbox', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('energy', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('system', 'System')], default='web', max_length=20)),
                ('source_user_id', models.CharField(blank=True, max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='productivity.goal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='productivity.project')),
            ],
            options={
                'ordering': ['status', 'priority', 'planned_date', 'due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'priority'], name='productivit_status_510bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['due_date'], name='productivit_due_dat_0553ee_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='productivit_status_11381e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['planned_date', 'status'], name='productivit_planned_ed469f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='productivit_due_dat_074785_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source', 'source_user_id'], name='productivit_source_84e2ee_idx'),
        ),
    ]
