# Generated by Django 5.2.15 on 2026-06-26 21:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(default='IDR', max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('provider', models.CharField(default='ExchangeRate-API Open Access', max_length=120)),
                ('provider_url', models.URLField(blank=True)),
                ('time_last_update', models.DateTimeField(blank=True, null=True)),
                ('time_next_update', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['base_currency', 'target_currency', '-fetched_at'], name='finance_exc_base_cu_6adfea_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyConversionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(max_length=3)),
                ('source_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('idr_rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('converted_idr_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.CharField(default='ExchangeRate-API Open Access', max_length=120)),
                ('rate_is_stale', models.BooleanField(default=False)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_checks', to='finance.exchangeratesnapshot')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['source_currency', '-checked_at'], name='finance_cur_source__bc5cb1_idx')],
            },
        ),
    ]
