# Generated by Django 5.2.15 on 2026-06-26 21:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_currency_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_class', models.CharField(choices=[('stock_id', 'Indonesia Stock'), ('stock_us', 'US Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Crypto'), ('bond', 'Bond'), ('cash_equivalent', 'Cash Equivalent'), ('other', 'Other')], max_length=30, unique=True)),
                ('target_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['asset_class'],
            },
        ),
        migrations.CreateModel(
            name='FinancialFreedomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=80, unique=True)),
                ('annual_expense', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fire_multiplier', models.DecimalField(decimal_places=2, default=25, max_digits=6)),
                ('target_monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('emergency_fund_months', models.DecimalField(decimal_places=2, default=6, max_digits=5)),
                ('risk_profile', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('aggressive', 'Aggressive')], default='balanced', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=160, unique=True)),
                ('type', models.CharField(max_length=60)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('reason', models.TextField()),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('action_type', models.CharField(blank=True, max_length=80)),
                ('related_model', models.CharField(blank=True, max_length=80)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ignored', 'Ignored'), ('done', 'Done')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', '-severity', '-estimated_amount', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=24)),
                ('provider_symbol', models.CharField(blank=True, max_length=40)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('market', models.CharField(choices=[('IDX', 'Indonesia'), ('US', 'United States'), ('GLOBAL', 'Global'), ('CRYPTO', 'Crypto'), ('OTHER', 'Other')], default='IDX', max_length=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('asset_class', models.CharField(choices=[('stock_id', 'Indonesia Stock'), ('stock_us', 'US Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('crypto', 'Crypto'), ('bond', 'Bond'), ('cash_equivalent', 'Cash Equivalent'), ('other', 'Other')], default='stock_id', max_length=30)),
                ('lot_size', models.DecimalField(decimal_places=4, default=100, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_watchlisted', models.BooleanField(default=False)),
                ('watch_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['market', 'symbol'],
                'constraints': [models.UniqueConstraint(fields=('market', 'symbol'), name='unique_instrument_market_symbol')],
            },
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('platform', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('fee', 'Fee'), ('split', 'Split')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('system', 'System')], default='web', max_length=20)),
                ('source_user_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('deleted', 'Deleted')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_transactions', to='finance.investmentaccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_transactions', to='finance.instrument')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'kind', 'status'], name='finance_inv_date_ea2efd_idx'), models.Index(fields=['instrument', 'status'], name='finance_inv_instrum_4d04e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('provider', models.CharField(default='Manual', max_length=80)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_stale', models.BooleanField(default=False)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='finance.instrument')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['instrument', '-fetched_at'], name='finance_pri_instrum_aa3519_idx')],
            },
        ),
    ]
