# Generated by Django 5.2.15 on 2026-06-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_investments_fire'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saving_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('top_leaks', models.JSONField(blank=True, default=list)),
                ('action_plan', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='is_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recurringrule',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('emergency_fund', 'Emergency Fund'), ('savings', 'Savings'), ('debt_payoff', 'Debt Payoff'), ('fire', 'FIRE'), ('large_purchase', 'Large Purchase'), ('other', 'Other')], default='savings', max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('monthly_target', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.debt')),
                ('linked_savings_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.savingsgoal')),
            ],
            options={
                'ordering': ['-is_active', 'priority', 'target_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=160, unique=True)),
                ('merchant', models.CharField(max_length=120)),
                ('note_pattern', models.CharField(blank=True, max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('occurrence_count', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('related_transaction_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_matches', to='finance.recurringrule')),
            ],
            options={
                'ordering': ['status', '-confidence', '-last_seen'],
            },
        ),
    ]
